[general]
library_name = "libcimgui"
output_file_path = "../src/LibCImGui.jl"
module_name = "LibCImGui"
jll_pkg_name = "CImGui_jll"
export_symbol_prefixes = ["ig", "Im"]
prologue_file_path = ""
epilogue_file_path = "./epilogue.jl"

